### ISSUE TITLE
Migration Fails on Clean DB

### ISSUE THREAD

**Issue by davidgrieser** [teoucsb82/rbghub#1]
When attempting to migrate from a empty DB the following errors is encountered. It doesn't look like the teams table migration exists.

```
==  AddUserIdToTeams: migrating ===============================================
-- add_column(:teams, :user_id, :integer)
rake aborted!
An error has occurred, this and all later migrations canceled:

SQLite3::SQLException: no such table: teams: ALTER TABLE "teams" ADD "user_id" integer/Users/david/.gem/ruby/2.0.0/gems/sqlite3-1.3.8/lib/sqlite3/database.rb:91:in `initialize'
```

**Comment by teoucsb82** [comment]
Ahh!! Somehow I was able to build past that last night, but just re-ran it
and you're right. Fixed the bad "teams" table error, triple checked, and
re-pushed the repo. Thank you!

On Wed, Mar 4, 2015 at 9:01 AM, David Grieser notifications@github.com
wrote:

> When attempting to migrate from a empty DB the following errors is
> encountered. It doesn't look like the teams table migration exists.
> 
> ==  AddUserIdToTeams: migrating ===============================================
> -- add_column(:teams, :user_id, :integer)
> rake aborted!
> An error has occurred, this and all later migrations canceled:
> 
> SQLite3::SQLException: no such table: teams: ALTER TABLE "teams" ADD "user_id" integer/Users/david/.gem/ruby/2.0.0/gems/sqlite3-1.3.8/lib/sqlite3/database.rb:91:in `initialize'
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/teoucsb82/rbghub/issues/1.

## 

http://www.dellamico.com

**Comment by davidgrieser** [comment]
Fixed. Thanks.
